worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    
    # Required for WebSocket upgrade handling.
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 0.0.0.0:443 ssl;
        listen [::]:443 ssl;
        server_name _;
        
        ssl_certificate "C:\Users\Harrison\Desktop\Development\Student_Search\localhost.crt";
        ssl_certificate_key "C:\Users\Harrison\Desktop\Development\Student_Search\localhost.key";


        # Proxy all frontend routes to Next.js
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

	location = /notifications/ws/placements {
  		proxy_pass http://127.0.0.1:8000/notifications/ws/placements;
  		proxy_http_version 1.1;
  		proxy_set_header Upgrade $http_upgrade;
  		proxy_set_header Connection "upgrade";
  		proxy_set_header Host $host;
  		proxy_set_header X-Forwarded-Proto $scheme;
  		proxy_read_timeout 3600s;
	}

        # Proxy API routes to FastAPI
        location /api/ {
            proxy_pass http://127.0.0.1:8000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
        }
    }

    server {
        listen 0.0.0.0:80;
        listen [::]:80;
        server_name _;
        return 301 https://$host$request_uri;
    }
}